### ISSUE TITLE
Deploying sinatra app

### ISSUE THREAD

**Issue by viktor-evdokimov** [Azure-App-Service/ruby#13]
I am looking into the way dockerfile is setup and `APP_COMMAND_LINE` configuration option mentioned in the readme does not seem to work.

So how do I configure ruby app to start my sinatra app with `ruby app.rb` ?

**Comment by dombarnes** [comment]
@viktor-evdokimov for my Sinatra app, I use `bundle exec puma config.ru -C config/puma.rb` assuming you have a `config.ru` file set up. Here's mine (for a modular sinatra app):
```
env = ENV.fetch('RACK_ENV', 'development')
require 'bundler'
require './config/environment'
require 'rack/protection'

Bundler.require(:default, env)
Dir.glob('./app/{models,helpers,extensions,jobs}/*.rb') { |file| 
  require file
}
require_relative './app/controllers/application_controller.rb'
Dir.glob('./app/controllers/*.rb') { |file| 
  require file
}

map '/' do
  use HomeController
end

run MyApp
```
