### ISSUE TITLE
Change in kudu causes bundled gems to fail when deployed to ruby containers

### ISSUE THREAD

**Issue by cardinal252** [Azure-App-Service/ruby#14]
Since the introduction of the change below (to the kudu container), our ruby based applications have failed to work correctly. The issue manifests as a failure to find libssl 1.0.2 in the ruby container. This I believe to be the result of the install of php5.6-soap during the container build.

Azure-App-Service/kudu@badcdc7#diff-06f3aff92fedcaa6c61de2dac226d693R311

Given php 5 support is required, the simplest solution would appear to be performing an install of the offending package (openssl-1.0.2 from php) on this container / re-releasing it if the base contains it already, but am open to other suggestions - maybe alternative php packages OR a way to lock the version its built against ?

Have raised a corresponding ticket here:

https://github.com/Azure-App-Service/kudu/issues/64

**Comment by patricklee2** [comment]
I think this was fixed with https://github.com/Azure-App-Service/ruby/pull/16
