### ISSUE TITLE
Container fails to start due to can't find bundle files in tmp/bundle

### ISSUE THREAD

**Issue by michelpf** [Azure-App-Service/ruby#15]
When I push the application, the container installs all gems in tmp/bundle, with no errors. But the docker log file presents an error regarding to startup. The error is the container can't find the gem files, especially the puma, in tmp/bundle. The files are in the location but the container is not able to find.

Any clues?

**Comment by michelpf** [comment]
I opened in incidente with Azure Support. They replicate the error and now the issue was addressed to Product Staff. As soon they answer the solution I'll put the answer.

**Comment by cardinal252** [comment]
This could be related to a change made in the ruby container, if you change your build to use the very latest ruby container I think it is now fixed.

**Comment by bendangelo** [comment]
Any updates on this?

**Comment by michelpf** [comment]
It was released new version of container few months ago. Now, is working like a charm. 😄
