### ISSUE TITLE
Bundle install never being called

### ISSUE THREAD

**Issue by dombarnes** [Azure-App-Service/ruby#17]
https://github.com/Azure-App-Service/ruby/blob/07bfef0afa990f0f3516aa96ed9ad310930dac32/2.3.3/startup.sh#L79

I'm currently testing this running locally on my dev machine, and when I perform `docker run` it exits because it says dependencies are missing
```
Running bundle check
You are replacing the current local value of path, which is currently nil
missing dependencies, try redeploying
```
Looking at `startup.sh` it looks like it checks if gems are zipped, if not, it sets the bundle path to vendor/bundle, then it does `bundle check` in `vendor/bundle` and exits out, because it's never going to reach the `bundle install` on L89-96.

Am I reading this wrong or should the bundle install action be happening elsewhere?

**Comment by patricklee2** [comment]
this is run to zip the gems before passing them to the ruby container https://github.com/Azure-App-Service/kudu/blob/master/kudu/deploy.bash.ruby.template
