### ISSUE TITLE
When will Ruby version is up?

### ISSUE THREAD

**Issue by emorima** [Azure-App-Service/ruby#20]
Current Ruby version for Azure Web App Service is 2.3.3.
The Latest Ruby versions are 2.3.8, 2.4.5 and 2.5.3.
(And Ruby's next version `2.6.0` will be released on 25 Dec.)

Some vulnerability are fixed since 2.3.3 until 2.3.8.
When will Ruby version is up?

I found this PR that is for Ruby' version up to 2.3.8 and 2.4.5, so I am very looking forward to merge this.
https://github.com/Azure-App-Service/ruby/pull/19

**Comment by uberllama** [comment]
I’m bumping this because the current scenario is pretty miserable. Is Ruby/Rails support effectively deprecated?

**Comment by patricklee2** [comment]
fixed
